name: build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xmake
      run: bash <(curl -fsSL https://xmake.io/shget.text)
    - name: Build
      run: echo 'y' | xmake -v
